apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: medlemskap
  name: medlemskap-analyse
  namespace: medlemskap

spec:
  ingresses:
    - https://medlemskap-analyse.intern.nav.no
    - https://medlemskap-analyse.ansatt.nav.no
  image: {{image}}
  port: 3000
  prometheus:
    enabled: true
    path: "/api/metrics"

  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
      claims:
        groups:
          - id: 29398a18-e5c3-4758-9001-56280e64f574
          - id: 00783459-173e-4782-97e0-712a178825fc
        extra:
          - azp_name
          - NAVident

    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:

  accessPolicy:
    outbound:
      rules:
        - application: medlemskap-analyse
        - application: nav-dekoratoren
          namespace: personbruker
        - application: medlemskap-saga
          namespace: medlemskap

  env:
    - NAIS_ENV: prod
    - name: SAGA_CLIENT
      value: api://prod-gcp.medlemskap.medlemskap-saga/.default
    - name: API_BASE_URL
      value: https://medlemskap-vurdering.intern.nav.no
  tokenx:
    enabled: true
