apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: medlemskap
  name: medlemskap-analyse
  namespace: medlemskap

spec:
  ingresses:
    - https://medlemskap-analyse.intern.dev.nav.no
    - https://medlemskap-analyse.ansatt.dev.nav.no
  image: {{image}}
  port: 3000
  prometheus:
    enabled: true
    path: "/api/metrics"

  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true
      claims:
        extra:
          - azp_name
          - NAVident

    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:

  accessPolicy:
    outbound:
      rules:
        - application: medlemskap-analyse
        - application: nav-dekoratoren
          namespace: personbruker
        - application: medlemskap-saga
          namespace: medlemskap

  env:
    - NAIS_ENV: dev
    - name: SAGA_CLIENT
      value: api://dev-gcp.medlemskap.medlemskap-saga/.default
    - name: API_BASE_URL
      value: https://medlemskap-vurdering.intern.dev.nav.no
  tokenx:
      enabled: true