name: Build & Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          persist-credentials: false
      - name: Build static files
        uses: docker/build-push-action@v5
        with:
          target: export
          outputs: type=local,dest=static
          secrets: NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}
      - name: Upload static files to NAV CDN
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: medlemskap
          source: ./static
          destination: "/_next"
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - name: Build and push docker image to GAR
        uses: nais/docker-build-push@main
        id: docker-push
        with:
          target: runtime
          team: medlemskap
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          build_secrets: NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}
  deploypreprod:
    name: Deploy to preprod
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: nais/deploy/actions/deploy@v2
        env:
          NAIS_ENV: dev
          CLUSTER: dev-gcp
          IMAGE: ${{ steps.docker-push.outputs.image }}
          RESOURCE: config/nais-dev.yml
  deployprod:
    name: Deploy to prod
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: nais/deploy/actions/deploy@v2
        env:
          NAIS_ENV: prod
          CLUSTER: prod-gcp
          IMAGE: ${{ steps.docker-push.outputs.image }}
          RESOURCE: config/nais-prod.yml
